
--changeset salvador:004-update-tabla
--preconditions onFail:MARK_RAN onError:MARK_RAN
ALTER TABLE public.CHARACTER
ADD COLUMN CREATED_AT TIMESTAMP NOT NULL;
ALTER TABLE public.CHARACTER
ADD COLUMN UPDATED_AT TIMESTAMP NOT NULL;

