spring:
  application:
    name: ${APPLICATION_NAME:liquibase-example,base-api}
  sleuth:
    baggage:
      remote-fields:
        - traceId
        - channelId
        - enterpriseId
      correlation-fields:
        - channelId
        - enterpriseId

springdoc:
  swagger-ui:
    path: /
---
server:
  port: ${PORT}
  servlet:
    context-path: /bff-or-api-or-acl/${VERSION}/seed

spring:
  config:
    activate:
      on-profile: default
    import: "configserver:"
  #cloud:
    #config:
      #uri: ${SPRING_CLOUD_CONFIG_URL}
      #label: ${SPRING_CLOUD_CONFIG_LABEL}
      #profile: ${SPRING_CLOUD_CONFIG_PROFILE}

rest:
  client:
    connect-timeout: ${service.timeout}
    read-timeout: 20000

async:
  default-executor:
    core-pool-size: 20
    max-pool-size: 50
    thread-name-prefix: "async-"
    queue-capacity: 100

seed:
  prefix: "BFF|API|ACL-SEE:"
  channel-id: ${mercury.channel.id}
  #auth-role-interceptor-enabled: true
  #security-headers:
    #allowed-origin:
    #allowed-methods: POST,GET,PUT,PATCH,DELETE,OPTIONS
    #allowed-headers: "Accept,Access-Control-Allowed-Origin,Access-Control-Allowed-Methods,\
      #Access-Control-Allowed-Headers,Authorization,Content-Type,clientenv,clientname,clientver,enterpriseid"
  character-repository:
    url: ${seed.character-repository.url}
  user-repository:
    url: ${users.api.uri}
---
spring:
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: health,refresh

rest:
  client:
    connect-timeout: 5000
    read-timeout: 10000

async:
  default-executor:
    core-pool-size: 10
    max-pool-size: 15
    thread-name-prefix: "async-"
    queue-capacity: 100

seed:
  prefix: "API-LIQ:"
  channel-id: I
  character-repository:
    url: https://swapi.dev/api/people/{id}/
  user-repository:
    url: https://mercury-back-inte.apps.ocp-np.sis.ad.bia.itau/api/v1/users
